import { Material } from "./material.js";

/**
 * Uniaxial bilinear `[strain, stress MPa]` points per material; see `material.ts` / `youngs-modulus.ts`.
 * Values are order-of-magnitude literature / handbook style for gameplay, not certified structural data.
 */
const noSolidCurve = {
    tensileYieldStrainStress: [0, 0] as const,
    tensileFractureStrainStress: [0, 0] as const,
    compressiveYieldStrainStress: [0, 0] as const,
    compressiveFractureStrainStress: [0, 0] as const,
};

const metaMaterialBase: Omit<Material, "baseColor"> = {
    metallic: 0.8,
    roughness: 0.2,
    irReflectance: 0.5,
    irEmission: 0,
    emissionRgb: [0, 0, 0],
    emissionMode: 0,
    density: 1200.0,
    viscosity: 0,
    specificHeatCapacity: Number.POSITIVE_INFINITY,
    thermalConductivity: 100.0,
    tensileYieldStrainStress: [0.01333, 40],
    tensileFractureStrainStress: [0.08, 48],
    compressiveYieldStrainStress: [-0.015, -45],
    compressiveFractureStrainStress: [-0.09, -52],
    restitution: 0.35,
};

export const definitions = {
    air: {
        baseColor: [1.0, 1.0, 1.0, 0.0],
        metallic: 0,
        roughness: 0,
        irReflectance: 0,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 1.225,
        viscosity: 0,
        specificHeatCapacity: 1006.0,
        thermalConductivity: 0.024,
        ...noSolidCurve,
        restitution: 0.0,
    },
    water: {
        baseColor: [0.0, 0.0, 1.0, 0.1],
        metallic: 0,
        roughness: 0,
        irReflectance: 0,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 997.0,
        viscosity: 1.0,
        specificHeatCapacity: 4200.0,
        thermalConductivity: 0.66,
        ...noSolidCurve,
        restitution: 0.05,
    },
    rock: {
        baseColor: [0.5, 0.5, 0.5, 1.0],
        metallic: 0,
        roughness: 0.8,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2650.0,
        viscosity: 0,
        specificHeatCapacity: 800.0,
        thermalConductivity: 4.0,
        tensileYieldStrainStress: [0.0016, 80],
        tensileFractureStrainStress: [0.002, 90],
        compressiveYieldStrainStress: [-0.0026, -130],
        compressiveFractureStrainStress: [-0.004, -160],
        restitution: 0.15,
    },
    ice: {
        baseColor: [0.8, 0.8, 1.0, 0.5],
        metallic: 0,
        roughness: 0.1,
        irReflectance: 0.2,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 917.0,
        viscosity: 0,
        specificHeatCapacity: 2040.0,
        thermalConductivity: 2.18,
        tensileYieldStrainStress: [0.00156, 15],
        tensileFractureStrainStress: [0.002, 18],
        compressiveYieldStrainStress: [-0.00365, -35],
        compressiveFractureStrainStress: [-0.005, -45],
        restitution: 0.2,
    },
    iron: {
        baseColor: [0.7, 0.7, 0.7, 1.0],
        metallic: 1.0,
        roughness: 0.3,
        irReflectance: 0.4,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 7874.0,
        viscosity: 0,
        specificHeatCapacity: 460.0,
        thermalConductivity: 50.0,
        tensileYieldStrainStress: [0.001, 200],
        tensileFractureStrainStress: [0.12, 350],
        compressiveYieldStrainStress: [-0.0011, -220],
        compressiveFractureStrainStress: [-0.11, -400],
        restitution: 0.45,
    },
    dirt: {
        baseColor: [0.4, 0.3, 0.2, 1.0],
        metallic: 0,
        roughness: 0.9,
        irReflectance: 0.05,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 1510.0,
        viscosity: 0,
        specificHeatCapacity: 800.0,
        thermalConductivity: 0.25,
        tensileYieldStrainStress: [0.04, 2],
        tensileFractureStrainStress: [0.08, 4],
        compressiveYieldStrainStress: [-0.12, -6],
        compressiveFractureStrainStress: [-0.2, -10],
        restitution: 0.05,
    },
    sand: {
        baseColor: [0.9, 0.8, 0.6, 1.0],
        metallic: 0,
        roughness: 0.8,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2100.0,
        viscosity: 0,
        specificHeatCapacity: 830.0,
        thermalConductivity: 0.2,
        tensileYieldStrainStress: [0.0125, 1],
        tensileFractureStrainStress: [0.025, 2],
        compressiveYieldStrainStress: [-0.05, -4],
        compressiveFractureStrainStress: [-0.09, -7],
        restitution: 0.15,
    },
    woodHard: {
        baseColor: [0.6, 0.4, 0.2, 1.0],
        metallic: 0,
        roughness: 0.7,
        irReflectance: 0.05,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 650.0,
        viscosity: 0,
        specificHeatCapacity: 2000.0,
        thermalConductivity: 0.16,
        tensileYieldStrainStress: [0.00375, 45],
        tensileFractureStrainStress: [0.04, 52],
        compressiveYieldStrainStress: [-0.0048, -58],
        compressiveFractureStrainStress: [-0.055, -68],
        restitution: 0.3,
    },
    woodSoft: {
        baseColor: [0.7, 0.5, 0.3, 1.0],
        metallic: 0,
        roughness: 0.8,
        irReflectance: 0.05,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 490.0,
        viscosity: 0,
        specificHeatCapacity: 2300.0,
        thermalConductivity: 0.12,
        tensileYieldStrainStress: [0.00389, 35],
        tensileFractureStrainStress: [0.045, 42],
        compressiveYieldStrainStress: [-0.00489, -44],
        compressiveFractureStrainStress: [-0.055, -54],
        restitution: 0.28,
    },
    steel: {
        baseColor: [0.55, 0.55, 0.6, 1.0],
        metallic: 1.0,
        roughness: 0.2,
        irReflectance: 0.3,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 7850.0,
        viscosity: 0,
        specificHeatCapacity: 490.0,
        thermalConductivity: 50.0,
        tensileYieldStrainStress: [0.00175, 350],
        tensileFractureStrainStress: [0.15, 500],
        compressiveYieldStrainStress: [-0.0019, -380],
        compressiveFractureStrainStress: [-0.13, -520],
        restitution: 0.55,
    },
    concrete: {
        baseColor: [0.6, 0.6, 0.6, 1.0],
        metallic: 0,
        roughness: 0.9,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2400.0,
        viscosity: 0,
        specificHeatCapacity: 880.0,
        thermalConductivity: 1.4,
        tensileYieldStrainStress: [0.000117, 3.5],
        tensileFractureStrainStress: [0.00015, 4],
        compressiveYieldStrainStress: [-0.00117, -35],
        compressiveFractureStrainStress: [-0.003, -40],
        restitution: 0.12,
    },
    reinforcedConcrete: {
        baseColor: [0.55, 0.55, 0.55, 1.0],
        metallic: 0.1,
        roughness: 0.9,
        irReflectance: 0.15,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2500.0,
        viscosity: 0,
        specificHeatCapacity: 880.0,
        thermalConductivity: 2.0,
        tensileYieldStrainStress: [0.00015, 4.5],
        tensileFractureStrainStress: [0.00022, 5.5],
        compressiveYieldStrainStress: [-0.0015, -45],
        compressiveFractureStrainStress: [-0.0035, -55],
        restitution: 0.14,
    },
    glass: {
        baseColor: [0.9, 0.95, 1.0, 0.3],
        metallic: 0,
        roughness: 0.05,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2500.0,
        viscosity: 0,
        specificHeatCapacity: 840.0,
        thermalConductivity: 1.0,
        tensileYieldStrainStress: [0.00043, 30],
        tensileFractureStrainStress: [0.0007, 35],
        compressiveYieldStrainStress: [-0.005, -350],
        compressiveFractureStrainStress: [-0.006, -400],
        restitution: 0.18,
    },
    temperedGlass: {
        baseColor: [0.5, 0.55, 0.6, 0.4],
        metallic: 0,
        roughness: 0.05,
        irReflectance: 0.15,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2500.0,
        viscosity: 0,
        specificHeatCapacity: 840.0,
        thermalConductivity: 1.0,
        tensileYieldStrainStress: [0.00171, 120],
        tensileFractureStrainStress: [0.004, 200],
        compressiveYieldStrainStress: [-0.00786, -550],
        compressiveFractureStrainStress: [-0.0095, -620],
        restitution: 0.22,
    },
    meta: {
        baseColor: [0.2, 0.6, 0.7, 1.0],
        ...metaMaterialBase,
    },
    marble: {
        baseColor: [0.9, 0.9, 0.9, 1.0],
        metallic: 0,
        roughness: 0.3,
        irReflectance: 0.2,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2700.0,
        viscosity: 0,
        specificHeatCapacity: 830.0,
        thermalConductivity: 1.4,
        tensileYieldStrainStress: [0.000455, 25],
        tensileFractureStrainStress: [0.00065, 30],
        compressiveYieldStrainStress: [-0.00173, -95],
        compressiveFractureStrainStress: [-0.00273, -125],
        restitution: 0.12,
    },
    granite: {
        baseColor: [0.8, 0.8, 0.8, 1.0],
        metallic: 0,
        roughness: 0.6,
        irReflectance: 0.15,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2700.0,
        viscosity: 0,
        specificHeatCapacity: 830.0,
        thermalConductivity: 1.4,
        tensileYieldStrainStress: [0.00222, 100],
        tensileFractureStrainStress: [0.0032, 120],
        compressiveYieldStrainStress: [-0.00422, -190],
        compressiveFractureStrainStress: [-0.00555, -230],
        restitution: 0.12,
    },
    metaRed: {
        baseColor: [1.0, 0.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    metaOrange: {
        baseColor: [1.0, 0.5, 0.0, 1.0],
        ...metaMaterialBase,
    },
    metaYellow: {
        baseColor: [1.0, 1.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    metaLime: {
        baseColor: [0.5, 1.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    metaGreen: {
        baseColor: [0.0, 1.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    metaTeal: {
        baseColor: [0.0, 1.0, 0.5, 1.0],
        ...metaMaterialBase,
    },
    metaCyan: {
        baseColor: [0.0, 1.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaBlue: {
        baseColor: [0.0, 0.5, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaIndigo: {
        baseColor: [0.25, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaViolet: {
        baseColor: [0.5, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaPurple: {
        baseColor: [0.75, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaMagenta: {
        baseColor: [1.0, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaPink: {
        baseColor: [1.0, 0.5, 0.75, 1.0],
        ...metaMaterialBase,
    },
    metaWhite: {
        baseColor: [1.0, 1.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    metaGray: {
        baseColor: [0.5, 0.5, 0.5, 1.0],
        ...metaMaterialBase,
    },
    metaBlack: {
        baseColor: [0.0, 0.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
} as const satisfies Record<string, Material>;
export type MaterialName = keyof typeof definitions;
