import { Material } from "./material.js";

// Meta material base properties (shared by all meta-color materials)
const metaMaterialBase: Omit<Material, "baseColor"> = {
    metallic: 0.8,
    roughness: 0.2,
    irReflectance: 0.5,
    irEmission: 0,
    emissionRgb: [0, 0, 0],
    emissionMode: 0,
    density: 10.0,
    viscosity: 0,
    specificHeatCapacity: Number.POSITIVE_INFINITY,
    thermalConductivity: 100.0,
};

export const materialDefinitions = {
    air: {
        baseColor: [1.0, 1.0, 1.0, 0.01],
        metallic: 0,
        roughness: 0,
        irReflectance: 0,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 0.001225,
        viscosity: 0,
        specificHeatCapacity: 1006.0,
        thermalConductivity: 0.024,
    },
    water: {
        baseColor: [0.0, 0.0, 1.0, 0.1],
        metallic: 0,
        roughness: 0,
        irReflectance: 0,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 0.997,
        viscosity: 1.0,
        specificHeatCapacity: 4200.0,
        thermalConductivity: 0.66,
    },
    rock: {
        baseColor: [0.5, 0.5, 0.5, 1.0],
        metallic: 0,
        roughness: 0.8,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.65,
        viscosity: 0,
        specificHeatCapacity: 800.0,
        thermalConductivity: 4.0,
    },
    ice: {
        baseColor: [0.8, 0.8, 1.0, 0.5],
        metallic: 0,
        roughness: 0.1,
        irReflectance: 0.2,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 0.997,
        viscosity: 0,
        specificHeatCapacity: 2040.0,
        thermalConductivity: 2.18,
    },
    iron: {
        baseColor: [0.7, 0.7, 0.7, 1.0],
        metallic: 1.0,
        roughness: 0.3,
        irReflectance: 0.4,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 7.874,
        viscosity: 0,
        specificHeatCapacity: 460.0,
        thermalConductivity: 50.0,
    },
    dirt: {
        baseColor: [0.4, 0.3, 0.2, 1.0],
        metallic: 0,
        roughness: 0.9,
        irReflectance: 0.05,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 1.51,
        viscosity: 0,
        specificHeatCapacity: 800.0,
        thermalConductivity: 0.25,
    },
    sand: {
        baseColor: [0.9, 0.8, 0.6, 1.0],
        metallic: 0,
        roughness: 0.8,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.1,
        viscosity: 0,
        specificHeatCapacity: 830.0,
        thermalConductivity: 0.2,
    },
    woodHard: {
        baseColor: [0.6, 0.4, 0.2, 1.0],
        metallic: 0,
        roughness: 0.7,
        irReflectance: 0.05,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 0.65,
        viscosity: 0,
        specificHeatCapacity: 2000.0,
        thermalConductivity: 0.16,
    },
    woodSoft: {
        baseColor: [0.7, 0.5, 0.3, 1.0],
        metallic: 0,
        roughness: 0.8,
        irReflectance: 0.05,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 0.49,
        viscosity: 0,
        specificHeatCapacity: 2300.0,
        thermalConductivity: 0.12,
    },
    steel: {
        baseColor: [0.55, 0.55, 0.6, 1.0],
        metallic: 1.0,
        roughness: 0.2,
        irReflectance: 0.3,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 7.85,
        viscosity: 0,
        specificHeatCapacity: 490.0,
        thermalConductivity: 50.0,
    },
    concrete: {
        baseColor: [0.6, 0.6, 0.6, 1.0],
        metallic: 0,
        roughness: 0.9,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.4,
        viscosity: 0,
        specificHeatCapacity: 880.0,
        thermalConductivity: 1.4,
    },
    reinforcedConcrete: {
        baseColor: [0.55, 0.55, 0.55, 1.0],
        metallic: 0.1,
        roughness: 0.9,
        irReflectance: 0.15,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.5,
        viscosity: 0,
        specificHeatCapacity: 880.0,
        thermalConductivity: 2.0,
    },
    glass: {
        baseColor: [0.9, 0.95, 1.0, 0.3],
        metallic: 0,
        roughness: 0.05,
        irReflectance: 0.1,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.5,
        viscosity: 0,
        specificHeatCapacity: 840.0,
        thermalConductivity: 1.0,
    },
    temperedGlass: {
        baseColor: [0.5, 0.55, 0.6, 0.4],
        metallic: 0,
        roughness: 0.05,
        irReflectance: 0.15,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.5,
        viscosity: 0,
        specificHeatCapacity: 840.0,
        thermalConductivity: 1.0,
    },
    meta: {
        baseColor: [0.2, 0.6, 0.7, 1.0],
        ...metaMaterialBase,
    },
    marble: {
        baseColor: [0.9, 0.9, 0.9, 1.0],
        metallic: 0,
        roughness: 0.3,
        irReflectance: 0.2,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.7,
        viscosity: 0,
        specificHeatCapacity: 830.0,
        thermalConductivity: 1.4,
    },
    granite: {
        baseColor: [0.8, 0.8, 0.8, 1.0],
        metallic: 0,
        roughness: 0.6,
        irReflectance: 0.15,
        irEmission: 0,
        emissionRgb: [0, 0, 0],
        emissionMode: 0,
        density: 2.7,
        viscosity: 0,
        specificHeatCapacity: 830.0,
        thermalConductivity: 1.4,
    },
    // Meta-color materials (painted materials sharing MetaMaterial properties)
    "meta-red": {
        baseColor: [1.0, 0.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-orange": {
        baseColor: [1.0, 0.5, 0.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-yellow": {
        baseColor: [1.0, 1.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-lime": {
        baseColor: [0.5, 1.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-green": {
        baseColor: [0.0, 1.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-teal": {
        baseColor: [0.0, 1.0, 0.5, 1.0],
        ...metaMaterialBase,
    },
    "meta-cyan": {
        baseColor: [0.0, 1.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-blue": {
        baseColor: [0.0, 0.5, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-indigo": {
        baseColor: [0.25, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-violet": {
        baseColor: [0.5, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-purple": {
        baseColor: [0.75, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-magenta": {
        baseColor: [1.0, 0.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-pink": {
        baseColor: [1.0, 0.5, 0.75, 1.0],
        ...metaMaterialBase,
    },
    "meta-white": {
        baseColor: [1.0, 1.0, 1.0, 1.0],
        ...metaMaterialBase,
    },
    "meta-gray": {
        baseColor: [0.5, 0.5, 0.5, 1.0],
        ...metaMaterialBase,
    },
    "meta-black": {
        baseColor: [0.0, 0.0, 0.0, 1.0],
        ...metaMaterialBase,
    },
} as const satisfies Record<string, Material>;
export type MaterialName = keyof typeof materialDefinitions;


