import { Store } from "@adobe/data/ecs";
import { AabbFace, Vec3 } from "@adobe/data/math";
import { TrueSchema } from "@adobe/data/schema";
import { GameService } from "game-service/game-service.js";
import { graphicsStoreSchema } from "graphics/database/graphics-store.js";

// Store Schema
export const schema = GameService.schema(
    {
        wall: TrueSchema,
        wallFace: AabbFace.schema,
        selectedFaces: AabbFace.schema,
        pickable: TrueSchema,
        selectedVoxelFace: TrueSchema,
        model: TrueSchema,
    },
    {
        modelSize: { default: [16, 16, 16] as Vec3 },
        pointerDown: { default: [] as ({ position: Vec3, face: AabbFace, select: boolean } | undefined)[], mutable: true }
    },
    {
        Pickable: ["pickable", ...graphicsStoreSchema.archetypes.Particle],
        Model: ["model", "pickable", ...graphicsStoreSchema.archetypes.Particle],
        Wall: ["wall", "wallFace", "pickable", ...graphicsStoreSchema.archetypes.Particle],
        // selection model, voxel position and selected faces.
        SelectedVoxel: ["selectedFaces", "position"],
        // visible display of selections generated by selected-voxel-visibility-system.
        SelectedVoxelFace: ["selectedVoxelFace", ...graphicsStoreSchema.archetypes.Particle],
    }
);

export type VoxelEditorStore = Store.FromSchema<typeof schema>;
