import { Store } from "@adobe/data/ecs";
import { AabbFace, Vec3 } from "@adobe/data/math";
import { TrueSchema } from "@adobe/data/schema";
import { GameService } from "game-service/game-service.js";
import { graphicsStoreSchema } from "graphics/database/graphics-store.js";
import { materials } from "physics/basic-materials.js";
import { MaterialIndex } from "physics/material.js";

// Store Schema
export const schema = GameService.schema(
    {
        wall: TrueSchema,
        wallFace: AabbFace.schema,
        selectedFaces: AabbFace.schema,
        pickable: TrueSchema,
        selectedVoxelFace: TrueSchema,
        model: TrueSchema,
        material: MaterialIndex.schema
    },
    {
        modelSize: { default: [16, 16, 16] as Vec3 },
        pointerDown: { default: [] as ({ position: Vec3, face: AabbFace, select: boolean, dragId: number } | undefined)[], mutable: true },
        selectedMaterial: { default: materials.rock.index as MaterialIndex },
        currentFile: { default: null as FileSystemFileHandle | null, mutable: true, transient: true },
        isDirty: { default: false as boolean, mutable: true },
        nextDragId: { default: 0 as number, mutable: true }
    },
    {
        Pickable: ["pickable", ...graphicsStoreSchema.archetypes.Particle],
        Model: ["model", "pickable", "material", ...graphicsStoreSchema.archetypes.Particle],
        Wall: ["wall", "wallFace", "pickable", "transient", ...graphicsStoreSchema.archetypes.Particle],
        // selection model, voxel position and selected faces.
        SelectedVoxel: ["selectedFaces", "position"],
        // visible display of selections generated by selected-voxel-visibility-system.
        SelectedVoxelFace: ["selectedVoxelFace", "transient", ...graphicsStoreSchema.archetypes.Particle],
    }
);

export type VoxelEditorStore = Store.FromSchema<typeof schema>;

export const createVoxelEditorStore = (): VoxelEditorStore => {
    // TODO: Fix this later.
    return Store.createFromSchema(schema as any) as unknown as VoxelEditorStore;
};
